name: "Push to Artifact Registry"
description: "A GitHub Action to Build and Push docker image to Google Cloud Artifact Registry."
inputs:
  gcp-project-id:
    description: "Google Cloud Platform project name."
    required: true
  gcp-region:
    description: "Google Cloud Platform Artifact Registry region."
    required: true
  gcp-sa:
    description: "Google Cloud Platform service account to log in Google Cloud SDK."
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/hsblhsn/push-to-artifact-registry:latest"
  args:
    - ${{ inputs.gcp-project-id }}
    - ${{ inputs.gcp-region }}
    - ${{ inputs.gcp-sa }}
branding:
  icon: "box"
  color: "blue"
