on:
  push:
    branches:
      - "!main"

jobs:
  build:
    name: Build docker image.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/push-to-artifact-registry:latest
